apiVersion: apps/v1
kind: Deployment
metadata:
  name: my node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my node-app
  template:
    metadata:
      labels:
        app: my node-app
    spec:
      containers:
      - name: my node-app
        image: jenilraj/node-app12
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
